routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Auth::routes();


Route::group(['middleware' => 'auth'], function () {
    Route::group(['prefix' => 'admin'], function () {
        Route::get('/dashboard', ['as' => 'dashboard', 'uses' => 'Back\HomeController@index']);

        Route::resource('winners', 'Back\WinnerController');
        Route::get('ajax_winners_all', ['as' => 'winners.data', 'uses' =>  'Back\WinnerController@allData']);
        Route::post('send_email/{id}', ['as' => 'winners.send', 'uses' =>  'Back\WinnerController@sendEmail']);

        Route::resource('contact_form', 'Back\ContactFormController');
        Route::get('ajax_contact_form_requests_all', ['as' => 'contact_form_requests.data', 'uses' =>  'Back\ContactFormController@anyData']);

        Route::resource('media', 'Back\MediaController');
        Route::post('upload/delete', ['as' => 'upload-remove', 'uses' =>'Back\MediaController@deleteUpload']);
        Route::get('upload/delete', [ 'uses' =>'Back\MediaController@deleteUpload']);

    });
});

Route::get('/', array('as' => 'homepage', 'uses' => 'Front\PageController@index'));
Route::get('ajax_all_winners', array( 'uses' => 'Front\PageController@showAllWinners'));

Route::post('contact-form', array('as' => 'contact.form','uses' => 'Front\PageController@contact'));
Route::post('participant', array('as' => 'participant.store','uses' => 'Front\PageController@storeParticipant'));
Route::get('admin',  function () {
    return redirect('admin/dashboard');
});
Route::get('{static}', array('uses' => 'Front\PageController@showPage'))->where('static', '(about|faq|prizes|rules|winners)');
;

resources/views/backend/includes/dashboard.blade.php
@extends('layouts.back')
@section('title', 'Dashboard')
@push('stylesheets')
@endpush

@section('main_container')

    <div class="row top_tiles">
        <div class="animated flipInY col-lg-4 col-md-4 col-sm-4 col-xs-12">
            <div class="tile-stats">
                <div class="icon"><i class="fa fa-users"></i></div>
                <div class="count">{{$participant_all}}</div>
                <h3>участников</h3>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
            </div>
        </div>
        <div class="animated flipInY col-lg-4 col-md-4 col-sm-4 col-xs-12">
            <div class="tile-stats">
                <div class="icon"><i class="fa fa-trophy"></i></div>
                <div class="count">{{$winners}}</div>
                <h3>победителей</h3>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
            </div>
        </div>
        <div class="animated flipInY col-lg-4 col-md-4 col-sm-4 col-xs-12">
            <div class="tile-stats">
                <div class="icon"><i class="fa fa-comment"></i></div>
                <div class="count">{{$contacts}}</div>
                <h3>собщений</h3>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
            </div>
        </div>
    </div>
@stop

@push('scripts')
@endpush

resources/views/backend/includes/email-template.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Discussion Update</title>
    <style type="text/css">
        /* -------------------------------------
            INLINED WITH https://putsmail.com/inliner
        ------------------------------------- */
        /* -------------------------------------
            RESPONSIVE AND MOBILE FRIENDLY STYLES
        ------------------------------------- */
        @media only screen and (max-width: 620px) {
            table[class=body] h1 {
                font-size: 28px !important;
                margin-bottom: 10px !important; }
            table[class=body] p,
            table[class=body] ul,
            table[class=body] ol,
            table[class=body] td,
            table[class=body] span,
            table[class=body] a {
                font-size: 16px !important; }
            table[class=body] .wrapper,
            table[class=body] .article {
                padding: 10px !important; }
            table[class=body] .content {
                padding: 0 !important; }
            table[class=body] .container {
                padding: 0 !important;
                width: 100% !important; }
            table[class=body] .main {
                border-left-width: 0 !important;
                border-radius: 0 !important;
                border-right-width: 0 !important; }
            table[class=body] .btn table {
                width: 100% !important; }
            table[class=body] .btn a {
                width: 100% !important; }
            table[class=body] .img-responsive {
                height: auto !important;
                max-width: 100% !important;
                width: auto !important; }}
        /* -------------------------------------
            PRESERVE THESE STYLES IN THE HEAD
        ------------------------------------- */
        @media all {
            .ExternalClass {
                width: 100%; }
            .ExternalClass,
            .ExternalClass p,
            .ExternalClass span,
            .ExternalClass font,
            .ExternalClass td,
            .ExternalClass div {
                line-height: 100%; }
            .apple-link a {
                color: inherit !important;
                font-family: inherit !important;
                font-size: inherit !important;
                font-weight: inherit !important;
                line-height: inherit !important;
                text-decoration: none !important; }
            .btn-primary table td:hover {
                background-color: #34495e !important; }
            .btn-primary a:hover {
                background-color: #34495e !important;
                border-color: #34495e !important; } }
    </style>
</head>
<body class="" style="background-color:#f6f6f6;font-family:sans-serif;-webkit-font-smoothing:antialiased;font-size:14px;line-height:1.4;margin:0;padding:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;">
<table border="0" cellpadding="0" cellspacing="0" class="body" style="border-collapse:separate;mso-table-lspace:0pt;mso-table-rspace:0pt;background-color:#f6f6f6;width:100%;">
    <tr>
        <td style="font-family:sans-serif;font-size:14px;vertical-align:top;">&nbsp;</td>
        <td class="container" style="font-family:sans-serif;font-size:14px;vertical-align:top;display:block;max-width:580px;padding:10px;width:580px;Margin:0 auto !important;">
            <div class="content" style="box-sizing:border-box;display:block;Margin:0 auto;max-width:580px;padding:10px;">
                <!-- START CENTERED WHITE CONTAINER -->
                <span class="preheader" style="color:transparent;display:none;height:0;max-height:0;max-width:0;opacity:0;overflow:hidden;mso-hide:all;visibility:hidden;width:0;"></span>
                <table class="main" style="border-collapse:separate;mso-table-lspace:0pt;mso-table-rspace:0pt;background:#fff;border-radius:3px;width:100%;">
                    <!-- START MAIN CONTENT AREA -->
                    <tr>
                        <td class="wrapper" style="font-family:sans-serif;font-size:14px;vertical-align:top;box-sizing:border-box;padding:20px;">
                            <table border="0" cellpadding="0" cellspacing="0" style="border-collapse:separate;mso-table-lspace:0pt;mso-table-rspace:0pt;width:100%;">
                                <tr>
                                    <td style="font-family:sans-serif;font-size:14px;vertical-align:top;">
                                        <p style="font-family:sans-serif;font-size:14px;font-weight:normal;margin:0;Margin-bottom:15px;">Добрый день,</p>
                                        <p style="font-family:sans-serif;font-size:14px;font-weight:normal;margin:0;Margin-bottom:15px;">просто хотели, чтобы Вы знали, что кто-то заполнил форму обратной связи на сайте.</p>
                                        <table border="0" cellpadding="0" cellspacing="0" style="border-collapse:separate;mso-table-lspace:0pt;mso-table-rspace:0pt;box-sizing:border-box;width:100%;">
                                            <tbody>
                                            <tr>
                                                <td align="left" style="font-family:sans-serif;font-size:14px;vertical-align:top;padding-bottom:15px;">
                                                    <table border="0" cellpadding="0" cellspacing="0" style="border-collapse:separate;mso-table-lspace:0pt;mso-table-rspace:0pt;width:100%;width:auto;">
                                                        <tbody>
                                                        <tr>
                                                            <td style="font-family:sans-serif;font-size:14px;vertical-align:top;color:#8c003b;"><strong>E-mail:</strong></td>
                                                            <td style="font-family:sans-serif;font-size:14px;vertical-align:top;">&nbsp; {{ $data['email'] }}</td>
                                                        </tr>
                                                        <tr>
                                                            <td style="font-family:sans-serif;font-size:14px;vertical-align:top;color:#8c003b;"><strong>Сообщение:</strong></td>
                                                            <td style="font-family:sans-serif;font-size:14px;vertical-align:top;">&nbsp; {!! nl2br(e($data['message'])) !!}</td>
                                                        </tr>
                                                        </tbody>
                                                    </table>
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                        <p style="font-family:sans-serif;font-size:14px;font-weight:normal;margin:0;Margin-bottom:15px;">Хорошего дня! С уважением, команда <a href="{{ url('/') }}" target="_blank" style="color:#8c003b;cursor:pointer;display:inline-block;font-size:14px;font-weight:bold;margin:0;text-decoration:none;text-transform:capitalize;">Faberlic</a></p>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                    <!-- END MAIN CONTENT AREA -->
                </table>
                <!-- END CENTERED WHITE CONTAINER -->
            </div>
        </td>
        <td style="font-family:sans-serif;font-size:14px;vertical-align:top;">&nbsp;</td>
    </tr>
</table>
</body>
</html>

resources/views/backend/includes/email-template_winner.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Discussion Update</title>
    <style type="text/css">
        /* -------------------------------------
            INLINED WITH https://putsmail.com/inliner
        ------------------------------------- */
        /* -------------------------------------
            RESPONSIVE AND MOBILE FRIENDLY STYLES
        ------------------------------------- */
        @media only screen and (max-width: 620px) {
            table[class=body] h1 {
                font-size: 28px !important;
                margin-bottom: 10px !important; }
            table[class=body] p,
            table[class=body] ul,
            table[class=body] ol,
            table[class=body] td,
            table[class=body] span,
            table[class=body] a {
                font-size: 16px !important; }
            table[class=body] .wrapper,
            table[class=body] .article {
                padding: 10px !important; }
            table[class=body] .content {
                padding: 0 !important; }
            table[class=body] .container {
                padding: 0 !important;
                width: 100% !important; }
            table[class=body] .main {
                border-left-width: 0 !important;
                border-radius: 0 !important;
                border-right-width: 0 !important; }
            table[class=body] .btn table {
                width: 100% !important; }
            table[class=body] .btn a {
                width: 100% !important; }
            table[class=body] .img-responsive {
                height: auto !important;
                max-width: 100% !important;
                width: auto !important; }}
        /* -------------------------------------
            PRESERVE THESE STYLES IN THE HEAD
        ------------------------------------- */
        @media all {
            .ExternalClass {
                width: 100%; }
            .ExternalClass,
            .ExternalClass p,
            .ExternalClass span,
            .ExternalClass font,
            .ExternalClass td,
            .ExternalClass div {
                line-height: 100%; }
            .apple-link a {
                color: inherit !important;
                font-family: inherit !important;
                font-size: inherit !important;
                font-weight: inherit !important;
                line-height: inherit !important;
                text-decoration: none !important; }
            .btn-primary table td:hover {
                background-color: #34495e !important; }
            .btn-primary a:hover {
                background-color: #34495e !important;
                border-color: #34495e !important; } }
    </style>
</head>
<body class="" style="background-color:#f6f6f6;font-family:sans-serif;-webkit-font-smoothing:antialiased;font-size:14px;line-height:1.4;margin:0;padding:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;">
<table border="0" cellpadding="0" cellspacing="0" class="body" style="border-collapse:separate;mso-table-lspace:0pt;mso-table-rspace:0pt;background-color:#f6f6f6;width:100%;">
    <tr>
        <td style="font-family:sans-serif;font-size:14px;vertical-align:top;">&nbsp;</td>
        <td class="container" style="font-family:sans-serif;font-size:14px;vertical-align:top;display:block;max-width:580px;padding:10px;width:580px;Margin:0 auto !important;">
            <div class="content" style="box-sizing:border-box;display:block;Margin:0 auto;max-width:580px;padding:10px;">
                <!-- START CENTERED WHITE CONTAINER -->
                <span class="preheader" style="color:transparent;display:none;height:0;max-height:0;max-width:0;opacity:0;overflow:hidden;mso-hide:all;visibility:hidden;width:0;"></span>
                <table class="main" style="border-collapse:separate;mso-table-lspace:0pt;mso-table-rspace:0pt;background:#fff;border-radius:3px;width:100%;">
                    <!-- START MAIN CONTENT AREA -->
                    <tr>
                        <td class="wrapper" style="font-family:sans-serif;font-size:14px;vertical-align:top;box-sizing:border-box;padding:20px;">
                            <table border="0" cellpadding="0" cellspacing="0" style="border-collapse:separate;mso-table-lspace:0pt;mso-table-rspace:0pt;width:100%;">
                                <tr>
                                    <td style="font-family:sans-serif;font-size:14px;vertical-align:top;">
                                        <p style="font-family:sans-serif;font-size:14px;font-weight:normal;margin:0;Margin-bottom:15px;">Добрый день,</p>
                                        <p style="font-family:sans-serif;font-size:14px;font-weight:normal;margin:0;Margin-bottom:15px;">Вы были выбраны победителем в Розыгрыше «Мое желание» от Faberlic.</p>

                                        <p style="font-family:sans-serif;font-size:14px;font-weight:normal;margin:0;Margin-bottom:15px;">Хорошего дня! С уважением, команда <a href="{{ url('/') }}" target="_blank" style="color:#8c003b;cursor:pointer;display:inline-block;font-size:14px;font-weight:bold;margin:0;text-decoration:none;text-transform:capitalize;">Faberlic</a></p>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                    <!-- END MAIN CONTENT AREA -->
                </table>
                <!-- END CENTERED WHITE CONTAINER -->
            </div>
        </td>
        <td style="font-family:sans-serif;font-size:14px;vertical-align:top;">&nbsp;</td>
    </tr>
</table>
</body>
</html>

resources/views/backend/includes/form.blade.php
@extends('layouts.back')
@section('title', $data->get('title'))
@push('stylesheets')@endpush

@section('main_container')

    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h4>{!! $data->get('title') !!}</h4>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="@if(!empty($data->get('features'))) col-md-9 col-sm-9 @else col-md-12 col-sm-12 @endif col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <ul class="nav navbar-left panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                        </ul>
                        @if(!empty($data->get('str_title')))
                            <h2><small>{{$data->get('str_title')}}</small></h2>
                        @endif
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <br />
                        @if(empty($record->id))
                            @if(!empty($data->get('var')))
                                {!!Form::model($record,['route' =>[$data->get('route'), $data->get('var')],
                                'data-parsley-validate',
                                'enctype'=>'multipart/form-data',
                                'class'=>'form-horizontal form-label-left'])!!}
                            @else
                                {!!Form::model($record,['route' =>[$data->get('route')],
                          'data-parsley-validate',
                          'enctype'=>'multipart/form-data',
                          'class'=>'form-horizontal form-label-left'])!!}
                            @endif
                        @else
                            @if(!empty($data->get('var')))
                                {!! Form::model($record, ['method' => 'PATCH',
                            'route' => [$data->get('route'), $data->get('var'),$record->id],

                            'data-parsley-validate','enctype'=>'multipart/form-data',
                            'class'=>'form-horizontal form-label-left']) !!}

                            @else
                                {!! Form::model($record, ['method' => 'PATCH',
                            'route' => [$data->get('route'),$record->id],

                            'data-parsley-validate','enctype'=>'multipart/form-data',
                            'class'=>'form-horizontal form-label-left']) !!}

                            @endif
                        @endif
                        @include( $data->get('include'),  ['submit_text' => $data->get('submit_text')])

                        @if(!empty($data->get('features')))
                            @if(empty($record->id))
                                <input type="hidden" name="{{$data->get('feature_name')}}" value="" id="hidden_input">
                            @else
                                <input type="hidden" name="{{$data->get('feature_name')}}" value="<?php $name = $data->get('feature_name'); echo $record[$name] ?>" id="hidden_input">
                            @endif
                        @endif
                        {!!Form::close()!!}

                    </div>
                </div>
            </div>
            @if(!empty($data->get('features')))
                <div class="col-md-3 col-sm-3 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Минюатюра <small>записи</small></h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content img_form">
                            <br />
                            @if(empty($record->id))
                                {!!Form::model(new App\Models\Media, ['route' =>  $data->get('route_feature'),
                                                                 'data-parsley-validate','files'=>true,
                                                                 'enctype'=>'multipart/form-data',
                                                                 'class'=>'dropzone', 'id'=>'my-dropzone'])!!}
                                {{ Form::close() }}
                            @elseif(!empty($record->id) && empty($record->media->id) )
                                {!!Form::model(new App\Models\Media, ['route' =>  'media.store',
                                                                     'data-parsley-validate','files'=>true,
                                                                     'enctype'=>'multipart/form-data',
                                                                     'class'=>'dropzone', 'id'=>'my-dropzone'])!!}
                                {{ Form::close() }}
                            @else
                                {{ Form::open(array('route' => array('media.destroy', $record->media->id), 'method' => 'delete', 'class'=>'','id'=>'img-del', 'data-parsley-validate','files'=>true )) }}

                                <img src="{{url('/uploads/admin/'.$record->media->title)}}" class="img-thumbnail"/>
                                <a data-del = "" class="btn btn-link pull-right delete-img">Удалить</a>
                                {{ Form::close() }}

                                {!!Form::model(new App\Models\Media, ['route' =>  'media.store',
                                                                'data-parsley-validate','files'=>true,
                                                                'enctype'=>'multipart/form-data',
                                                                'class'=>'dropzone ', 'id'=>'my-dropzone', 'style'=>'display: none'])!!}
                                {{ Form::close() }}
                            @endif
                        </div>
                    </div>
                </div>
            @endif
        </div>
    </div>
@stop

@push('scripts')
<script>

    /*DropZone */
    var fileList = new Array;
    Dropzone.options.myDropzone = {
        maxFiles: 1,
        paramName: "image",
        maxFilesize: 5,
        addRemoveLinks: true,
        dictRemoveFile: 'удалить',
        acceptedFiles: '.jpg, .jpeg, .png',
        dictFileTooBig: 'Image is bigger than 5MB',

        accept: function(file, done) {
            done();
        },
        success: function(file, response){
            $('#hidden_input').val(response.id);
            fileList = {"serverFileName" : response.title, "fileName" : response.name,"fileId" : response.id};
        },
        init: function() {
            this.on("maxfilesexceeded", function(file){
                alert("Не больше одного файла, пожалуйста");
            });

            this.on("removedfile", function(file) {
                var rmvFile = "";
                if(fileList.fileName == file.name)
                {
                    rmvFile = fileList.fileId;
                }

                if (rmvFile){
                    var url = APP_URL + '/admin/upload/delete';
                    $.ajax({
                        type: 'POST',
                        url: url,
                        data: {id: rmvFile, _token: $('meta[name="csrf-token"]').attr('content')},
                        dataType: 'html',
                        success: function(data){
                            $('#hidden_input').val('');
                        }
                    });

                }
            } );
        }

    };

    $('a.delete-img').on('click', function () {

        var form = $('#img-del');
        var form1 = $('#my-dropzone');
        var rowRoute = form.attr("action");
        var rowToken = $('meta[name="csrf-token"]').attr('content');
        var img = $('.img-thumbnail');
        deleteImg(rowRoute, rowToken, img);
        function deleteImg(rowRoute, rowToken, img)
        {
            $.ajax({
                headers: { 'X-CSRF-TOKEN' : rowToken},
                url: rowRoute,
                type: "POST",
                data: { _method:"DELETE" },

                success: function() {
                    form.remove();
                    form1.css('display','block');
                    $('#hidden_input').val('');
                },
                error: function() {
                    swal("Oops", "The Connection to the Server Failed", "Error");
                }
            })

        }
    });

</script>
@endpush

resources/views/backend/includes/sidebar.blade.php
<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <a href="{{ url('/') }}" class="site_title"><i class="fa fa-arrow-left"></i>&nbsp;&nbsp;<span>Faberlic</span></a>
        </div>
        
        <div class="clearfix"></div>

        <br />
        
        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <h3>&nbsp;</h3>
                <ul class="nav side-menu">
                    <li><a href="{{route('winners.index')}}"><i class="fa fa-trophy"></i>Победители</a></li>
                    <li><a href="{{route('contact_form.index')}}"><i class="fa fa-comment-o"></i>Сообщения</a></li>
                    <li><a href="{{route('dashboard')}}"><i class="fa fa-tachometer"></i>Итоги</a></li>
                </ul>
            </div>
        </div>
        <!-- /sidebar menu -->
        
        <!-- /menu footer buttons -->
        <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Logout" href="{{ url('/logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
        </div>
        <!-- /menu footer buttons -->
    </div>
</div>

resources/views/backend/includes/sub_form.blade.php
{!! Form::model($data->get('header'), ['method' => 'PATCH',
'route' => ['headers.update', $data->get('header')->id],
'data-parsley-validate','enctype'=>'multipart/form-data',
'class'=>'form-horizontal form-label-left']) !!}
<div class="input-group">
    {!! Form::text('title', $data->get('header')['title'], ['class'=>'form-control', 'placeholder'=>'Заголовок секции', 'id'=>'', 'required'] ) !!}
    <span class="input-group-btn"><button  type="submit" class="btn btn-primary">Изменить заголовок</button></span>
</div>
{!!Form::close()!!}

resources/views/backend/includes/table-head.blade.php
<thead>
<tr>
    @foreach( $data->get('table-head') as $th)
        <th>{{$th}}<br></th>
    @endforeach
</tr>
</thead>

resources/views/backend/includes/topbar.blade.php
<!-- top navigation -->
<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>
            
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <img src="{{ Gravatar::src(Auth::user()->email) }}" alt="Avatar of {{ Auth::user()->name }}">
                        {{ Auth::user()->name }}
                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li><a href="{{ url('/logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</div>
<!-- /top navigation -->

<form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
    {{ csrf_field() }}
</form>